version: '3.7'
services:

  proget-nginx:
    image: nginx:alpine
    container_name: proget-nginx
    hostname: proget-nginx
    volumes:
      - ./files/nginx/nginx.conf:/etc/nginx/nginx.conf
      - proget-nginx-logs:/var/log/nginx
    ports:
      - 80:80
    networks:
      - proget
    depends_on:
      - proget
      - proget-db

  proget-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: proget-db
    hostname: proget-db
    restart: unless-stopped
    user: root
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: Express
      MSSQL_SA_PASSWORD: <password>
    volumes:
      - proget-db-data:/var/opt/mssql/data
    networks:
      - proget

  proget:
    image: proget:5.3.3
    build:
      context: build/proget
      args:
        PROGET_VERSION: 5.3.3
    container_name: proget
    hostname: proget
    restart: unless-stopped
    environment:
      PROGET_DB_TYPE: SqlServer
      PROGET_DB_HOST: proget-db
      PROGET_DB_NAME: ProGet
      PROGET_DB_USER: sa
      PROGET_DB_PASS: <password>
    expose:
      - "80"
    volumes:
      - proget-packages:/var/proget/packages
      - proget-extensions:/var/proget/extensions
      - proget-sharedconfig:/usr/share/Inedo/SharedConfig
    networks:
      - proget
    depends_on:
      - proget-db

networks:
  proget:
    name: proget

volumes:
  proget-nginx-logs:
  proget-db-data:
  proget-packages:
  proget-extensions:
  proget-sharedconfig: